### ISSUE TITLE
Can you add proxy settings?        

### ISSUE THREAD

**Issue by NormanMises** [horsaen/afreeca-downloader#4]
Thanks for the program, it works fine on my windows computer!
However, can you add a proxy setting? You can set a separate proxy setting for each platform's recording, because sometimes I can't get the live stream 🥲 on my network environment

**Comment by horsaen** [comment]
hey !! sorry for not getting to this sooner, before i add something like this, i'd just like to know in case your issue can be solved an easier way -- what kind of issues are you met with ? is it possible for you to attach the command's output ? :]

thanks for the issue !!
