### ISSUE TITLE
binary closing byself dont know why

### ISSUE THREAD

**Issue by strongerr1234** [horsaen/afreeca-downloader#8]
hi binary is closing byself but dont know why? This has started happening lately. thx

**Comment by horsaen** [comment]
please make sure to add terminal output to issues -- without any sort of output i have no idea what the issue could be.

**Comment by strongerr1234** [comment]
> please make sure to add terminal output to issues -- without any sort of output i have no idea what the issue could be.

understood but there no any output for this issues. so binary closing byself :(
